steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - get_links
      - --region=us-central1
      - --source=.
      - --trigger-http
      - --runtime=python39
      - --memory=8Gb
      - --timeout=530
      - --min-instances=0
      - --max-instances=10
      - --security-level=secure-always
      - --ingress-settings=all
      - --no-allow-unauthenticated
      - --service-account=pavan-account@gcp-selenium.iam.gserviceaccount.com